---
version: "3.7"
services:
  db:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      # See: https://github.com/docker-library/postgres/pull/658. Alternatively,
      # DATABASE_HOST: "db"
      # POSTGRES_USER: "postgres"
    image: postgres:15
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7.0.10-alpine
    ports:
      - "6379:6379"
  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - "db"
      - "redis"
    environment:
      REDIS_URL: redis://redis:6379/12
    volumes:
      - ".:/project"
      - "/project/tmp" # don't mount tmp directory
volumes:
  db_data:
